window.getVALOQuizData = function () {
  return [
    // ★ normal（基本知識）
    {
      difficulty: 'normal',
      question: 'ヴァロラントのラウンド数の上限は何ラウンド？',
      choices: ['24ラウンド', '25ラウンド', '26ラウンド', '30ラウンド'],
      answer: 3,
    },
    {
      difficulty: 'normal',
      question: 'ヘッドショットで一撃キルが可能な武器は？',
      choices: ['ヴァンダル', 'スペクター', 'ゴースト', 'バッキー'],
      answer: 0,
    },
    {
      difficulty: 'normal',
      question: '「オーメン」の役割は何？',
      choices: ['デュエリスト', 'センチネル', 'イニシエーター', 'コントローラー'],
      answer: 3,
    },
    {
      difficulty: 'normal',
      question: 'アルティメットポイントはいくつで発動可能？',
      choices: ['5ポイント', '6ポイント', '7ポイント', '8ポイント'],
      answer: 2,
    },
    {
      difficulty: 'normal',
      question: '「ヘイヴン」マップにはいくつのサイトがある？',
      choices: ['2つ', '3つ', '4つ', '5つ'],
      answer: 1,
    },
    {
      difficulty: 'normal',
      question: '武器購入フェーズの時間は？',
      choices: ['20秒', '30秒', '40秒', '60秒'],
      answer: 1,
    },
    {
      difficulty: 'normal',
      question: '「レイズ」のグレネードの正式名称は？',
      choices: ['ボムボット', 'ペイント弾', 'ブラストパック', 'サテライト'],
      answer: 1,
    },
    {
      difficulty: 'normal',
      question: '「セージ」のスロウオーブはどんな効果？',
      choices: ['視界遮断', '回復', '移動速度減少', 'スタン'],
      answer: 2,
    },
    {
      difficulty: 'normal',
      question: 'スパイク設置後の爆発時間は？',
      choices: ['30秒', '35秒', '40秒', '45秒'],
      answer: 2,
    },
    {
      difficulty: 'normal',
      question: 'フラッシュを持つキャラは？',
      choices: ['ブリーチ', 'セージ', 'キルジョイ', 'ヴァイパー'],
      answer: 0,
    },
    {
      difficulty: 'normal',
      question: '「フェニックス」の役割は？',
      choices: ['デュエリスト', 'センチネル', 'コントローラー', 'イニシエーター'],
      answer: 0,
    },
    {
      difficulty: 'normal',
      question: '「ショーティ」は何系の武器？',
      choices: ['サブマシンガン', 'ショットガン', 'ピストル', 'ライフル'],
      answer: 1,
    },
    {
      difficulty: 'normal',
      question: '「アセント」マップの中央にある特徴は？',
      choices: ['スモーク', 'シャッター付きの扉', 'ジャンプ台', '自動タレット'],
      answer: 1,
    },
    {
      difficulty: 'normal',
      question: 'オーメンのスモークスキル名は？',
      choices: ['パラノイア', 'シュラウドステップ', 'ダークカヴァー', 'シャドウスライド'],
      answer: 2,
    },
    {
      difficulty: 'normal',
      question: '「ジェット」のウルトは何？',
      choices: ['ナイフを投げる', '爆弾を設置する', '敵をマーキング', '透明化'],
      answer: 0,
    },
    {
      difficulty: 'normal',
      question: '武器「スペクター」は何のカテゴリ？',
      choices: ['ライフル', 'サブマシンガン', 'スナイパーライフル', 'ショットガン'],
      answer: 1,
    },
    {
      difficulty: 'normal',
      question: 'エコラウンドの目的は？',
      choices: ['敵を倒す', '勝つ', 'お金を節約する', 'ウルトをためる'],
      answer: 2,
    },
    {
      difficulty: 'normal',
      question: 'キルジョイのアルティメットの効果は？',
      choices: ['敵の武器を無効化', '敵をスローにする', '敵を拘束する', '敵を浮かせる'],
      answer: 2,
    },
    {
      difficulty: 'normal',
      question: '「スモーク」は何の効果がある？',
      choices: ['ダメージ', '視界遮断', 'スロー', '回復'],
      answer: 1,
    },
    {
      difficulty: 'normal',
      question: '「ランク戦」は何レベルで開放？',
      choices: ['5レベル', '10レベル', '15レベル', '20レベル'],
      answer: 1,
    },

    // ★ hard（応用・中級者向け）
    {
      difficulty: 'hard',
      question: '「ヴァンダル」のヘッドショットダメージは何ダメージ？',
      choices: ['140', '150', '156', '160'],
      answer: 2,
    },
    {
      difficulty: 'hard',
      question: 'スパイク設置で得られるクレジットは？',
      choices: ['200', '300', '400', '600'],
      answer: 1,
    },
    {
      difficulty: 'hard',
      question: 'ソーヴァのアルティメットの名前は？',
      choices: ['オウルドローン', 'ショックボルト', 'ハンターズフューリー', 'リコンボルト'],
      answer: 2,
    },
    {
      difficulty: 'hard',
      question: '「スティンガー」の価格は？',
      choices: ['850', '950', '1100', '1200'],
      answer: 3,
    },
    {
      difficulty: 'hard',
      question: '「アイスボックス」の特徴は？',
      choices: ['中央のタワー', 'ロープ', '上下の高低差', '可動式の壁'],
      answer: 2,
    },
    {
      difficulty: 'hard',
      question: 'ソーヴァのリコンボルトは何回まで跳ね返る？',
      choices: ['1回', '2回', '3回', '4回'],
      answer: 2,
    },
    {
      difficulty: 'hard',
      question: 'レイズのアルティメットで倒せる最大人数は？',
      choices: ['1人', '2人', '3人', '理論上は5人'],
      answer: 3,
    },
    {
      difficulty: 'hard',
      question: 'ラウンド開始時に買えない武器は？',
      choices: ['クラシック', 'オーディン', 'ファントム', 'スペクター'],
      answer: 1,
    },
    {
      difficulty: 'hard',
      question: '味方へのヒールが可能なキャラは？',
      choices: ['ブリーチ', 'セージ', 'ヴァイパー', 'ブリムストーン'],
      answer: 1,
    },
    {
      difficulty: 'hard',
      question: 'ファントムの壁抜き性能は？',
      choices: ['低', '中', '高', '超高'],
      answer: 1,
    },
    {
      difficulty: 'hard',
      question: 'キルジョイのタレットの射程は？',
      choices: ['10m', '20m', '25m', '30m'],
      answer: 2,
    },
    {
      difficulty: 'hard',
      question: 'オーメンの「パラノイア」は何効果？',
      choices: ['スロー', '目くらまし', 'サイレンス', 'スネア'],
      answer: 1,
    },
    {
      difficulty: 'hard',
      question: 'アルティメットが最も早く貯まるキャラは？',
      choices: ['レイズ', 'フェニックス', 'ジェット', 'セージ'],
      answer: 2,
    },
    {
      difficulty: 'hard',
      question: '「ブリーチ」のフラッシュは何を通せる？',
      choices: ['壁', 'スモーク', '敵', '床'],
      answer: 0,
    },
    {
      difficulty: 'hard',
      question: '「ヴァイパー」のウルト中にできることは？',
      choices: ['透明化', '敵をマーク', '範囲攻撃', '酸の霧を維持'],
      answer: 3,
    },
    {
      difficulty: 'hard',
      question: '「ジェット」の上昇スキルの名前は？',
      choices: ['アセント', 'ライズ', 'アップドラフト', 'ウィンドジャンプ'],
      answer: 2,
    },
    {
      difficulty: 'hard',
      question: 'モロトフを使うキャラは？',
      choices: ['フェニックス', 'ブリムストーン', 'レイズ', 'オーメン'],
      answer: 1,
    },
    {
      difficulty: 'hard',
      question: '「フラクチャー」の特殊ギミックは？',
      choices: ['昇降機', '壁通過ポータル', '2つのスパウン', '可動式障壁'],
      answer: 2,
    },
    {
      difficulty: 'hard',
      question: 'マッチドロー後の延長ルールは？',
      choices: ['サドンデス', 'フルラウンド再試合', '先に2連勝', 'ランダム勝敗'],
      answer: 2,
    },
    {
      difficulty: 'hard',
      question: '「ヘイヴン」のAサイトの特徴は？',
      choices: ['ダブルドア', 'ワンウェイスモーク', '高所', '直通シャワー'],
      answer: 0,
    },
    // ★ veryhard（上級者・競技レベル）
    {
      difficulty: 'veryhard',
      question: '「アセント」でミッドからAサイトに進行する際、警戒すべき主なポジションは？',
      choices: ['ジェネレーター', 'ワイン', 'ツリー', 'ボートハウス'],
      answer: 2,
    },
    {
      difficulty: 'veryhard',
      question: 'オーメンの「ダークカヴァー」は最大で何秒間持続？',
      choices: ['10秒', '12秒', '14.25秒', '15秒'],
      answer: 2,
    },
    {
      difficulty: 'veryhard',
      question: 'ソーヴァの「ハンターズフューリー」は最大何回ヒット可能？',
      choices: ['2回', '3回', '4回', '5回'],
      answer: 1,
    },
    {
      difficulty: 'veryhard',
      question: 'ブリムストーンのスティムビーコンは何秒持続？',
      choices: ['8秒', '10秒', '12秒', '15秒'],
      answer: 0,
    },
    {
      difficulty: 'veryhard',
      question: 'ヴァイパーの「ヴァイパーズピット」の直径は？',
      choices: ['10m', '15m', '20m', '25m'],
      answer: 1,
    },
    {
      difficulty: 'veryhard',
      question: '「ロータス」のCサイトへ進行できるルートの数は？',
      choices: ['1つ', '2つ', '3つ', '4つ'],
      answer: 2,
    },
    {
      difficulty: 'veryhard',
      question: 'キルジョイの「ロックダウン」は何秒で爆発する？',
      choices: ['5秒', '7秒', '10秒', '13秒'],
      answer: 3,
    },
    {
      difficulty: 'veryhard',
      question: 'フェイドの「ナイトフォール」は何秒間敵の音を聞き取れる？',
      choices: ['6秒', '8秒', '12秒', '15秒'],
      answer: 1,
    },
    {
      difficulty: 'veryhard',
      question: 'チェンバーのアルティメットの正式名称は？',
      choices: ['トレードマーク', 'ランデブー', 'ツール・ド・フォース', 'バレット・クラッシュ'],
      answer: 2,
    },
    {
      difficulty: 'veryhard',
      question: 'ヨルのテレポートマーカーは最大で何秒残る？',
      choices: ['15秒', '20秒', '30秒', '無限'],
      answer: 2,
    },
    {
      difficulty: 'veryhard',
      question: '「アイスボックス」のBサイトにある高台の通称は？',
      choices: ['イエロー', 'オレンジ', 'スノーマン', 'ネスト'],
      answer: 3,
    },
    {
      difficulty: 'veryhard',
      question: '「パール」マップで使用される特殊オブジェクトは？',
      choices: ['可動壁', 'ジャンプ台', 'ドア', '何もない'],
      answer: 3,
    },
    {
      difficulty: 'veryhard',
      question: 'ゲッコーのモッシュピットの最大ダメージ範囲は？',
      choices: ['3m', '4.5m', '5m', '6m'],
      answer: 1,
    },
    {
      difficulty: 'veryhard',
      question: 'ネオンのオーバードライブでのヘッドショットダメージは？',
      choices: ['15', '20', '22', '26'],
      answer: 2,
    },
    {
      difficulty: 'veryhard',
      question: 'スパイク解除の所要時間は？',
      choices: ['4秒', '5秒', '6秒', '7秒'],
      answer: 2,
    },
    {
      difficulty: 'veryhard',
      question: 'ブリーチの「ローリングサンダー」は何段階で衝撃を与える？',
      choices: ['2段階', '3段階', '5段階', '7段階'],
      answer: 3,
    },
    {
      difficulty: 'veryhard',
      question: '「バインド」のテレポーターの音は何m先まで聞こえる？',
      choices: ['10m', '20m', '30m', 'マップ全体'],
      answer: 2,
    },
    {
      difficulty: 'veryhard',
      question: 'サイファーの「ニューラルセフト」はどの状態の敵に使用可能？',
      choices: ['生存中', 'ノックダウン中', '死亡後のみ', '味方に'],
      answer: 2,
    },
    {
      difficulty: 'veryhard',
      question: 'スモークを敵に撃つときに有利になるのは？',
      choices: ['中央に撃つ', 'エッジに撃つ', '内部に撃つ', '真上に撃つ'],
      answer: 1,
    },
    {
      difficulty: 'veryhard',
      question: 'クロスヘアの最適な設定は？',
      choices: ['緑で大きめ', '透明で細い', '見やすく敵を狙いやすい色とサイズ', '赤くて太く'],
      answer: 2,
    },
  ];
};
